import type { DataEntityDef } from "../explorer/provider.js";

export const TFL_REFERENCE_ENTITIES: DataEntityDef[] = [
  {
    id: "entity-tube-stations",
    label: "Tube Stations",
    description:
      "NaptanIDs for London Underground stations — use with StopPoint Arrivals and StopPoint Details",
    rows: [
      { name: "Aldgate", id: "940GZZLUALD" },
      { name: "Angel", id: "940GZZLUAGL" },
      { name: "Baker Street", id: "940GZZLUBKR" },
      { name: "Bank / Monument", id: "940GZZLUBNK" },
      { name: "Barbican", id: "940GZZLUBBN" },
      { name: "Bermondsey", id: "940GZZLUBMY" },
      { name: "Borough", id: "940GZZLUBRO" },
      { name: "Brixton", id: "940GZZLUBXN" },
      { name: "Canary Wharf", id: "940GZZLUCWR" },
      { name: "Cannon Street", id: "940GZZLUCST" },
      { name: "Clapham Common", id: "940GZZLUCPC" },
      { name: "Clapham North", id: "940GZZLUCPN" },
      { name: "Clapham South", id: "940GZZLUCPS" },
      { name: "Elephant & Castle", id: "940GZZLUEAC" },
      { name: "Euston", id: "940GZZLUEUS" },
      { name: "Farringdon", id: "940GZZLUFCN" },
      { name: "Finsbury Park", id: "940GZZLUFPK" },
      { name: "Green Park", id: "940GZZLUGPK" },
      { name: "Holborn", id: "940GZZLUHBN" },
      { name: "King's Cross St. Pancras", id: "940GZZLUKSX" },
      { name: "Knightsbridge", id: "940GZZLUKNB" },
      { name: "Liverpool Street", id: "940GZZLULVS" },
      { name: "London Bridge", id: "940GZZLULNB" },
      { name: "Moorgate", id: "940GZZLUMGT" },
      { name: "Old Street", id: "940GZZLUOLD" },
      { name: "Oxford Circus", id: "940GZZLUOXC" },
      { name: "Paddington", id: "940GZZLUPAC" },
      { name: "Pimlico", id: "940GZZLUPCO" },
      { name: "Sloane Square", id: "940GZZLUSQS" },
      { name: "Southwark", id: "940GZZLUSWK" },
      { name: "St. James's Park", id: "940GZZLUSJP" },
      { name: "St. Paul's", id: "940GZZLUSPU" },
      { name: "Stockwell", id: "940GZZLUSKW" },
      { name: "Stratford", id: "940GZZLUSTA" },
      { name: "Tower Hill", id: "940GZZLUTOH" },
      { name: "Vauxhall", id: "940GZZLUVXH" },
      { name: "Victoria", id: "940GZZLUVIC" },
      { name: "Waterloo", id: "940GZZLUWLO" },
      { name: "Westminster", id: "940GZZLUWSM" },
    ],
  },
  {
    id: "entity-tube-lines",
    label: "Tube Lines",
    description: "TfL line IDs for use in Line endpoints, status queries, and route filters",
    rows: [
      { name: "Bakerloo", id: "bakerloo" },
      { name: "Central", id: "central" },
      { name: "Circle", id: "circle" },
      { name: "District", id: "district" },
      { name: "DLR", id: "dlr" },
      { name: "Elizabeth line", id: "elizabeth" },
      { name: "Hammersmith & City", id: "hammersmith-city" },
      { name: "Jubilee", id: "jubilee" },
      { name: "London Overground", id: "london-overground" },
      { name: "Metropolitan", id: "metropolitan" },
      { name: "Northern", id: "northern" },
      { name: "Piccadilly", id: "piccadilly" },
      { name: "Tram", id: "tram" },
      { name: "Victoria", id: "victoria" },
      { name: "Waterloo & City", id: "waterloo-city" },
    ],
  },
  {
    id: "entity-bus-stops",
    label: "Bus Stops",
    description:
      "Search for London bus stops by name or area — results show NaptanIDs for use in StopPoint endpoints",
    search: {
      kind: "tfl-bus-stops",
      placeholder: "Search stops…",
      buttonLabel: "Search",
    },
  },
  {
    id: "entity-modes",
    label: "Transport Modes",
    description: "Mode identifiers accepted by StopPoint and Line endpoints",
    rows: [
      { name: "Bus", id: "bus" },
      { name: "Cable Car", id: "cable-car" },
      { name: "Coach", id: "coach" },
      { name: "DLR", id: "dlr" },
      { name: "Elizabeth line", id: "elizabeth-line" },
      { name: "National Rail", id: "national-rail" },
      { name: "Overground", id: "overground" },
      { name: "River Bus", id: "river-bus" },
      { name: "Tram", id: "tram" },
      { name: "Tube", id: "tube" },
      { name: "Walking", id: "walking" },
    ],
  },
];
